<a href="https://colab.research.google.com/github/janevnglst/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment3_Evangelista_Esteban.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CHE

## Assignment 3: matrices

Now that you have a fundamental knowledge about Phyton, we'll try to look into greater dimensions.

### Objectives

1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations
3. Program and translate matrix equations and operations using Phyton.

## Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have *A* and *B*  as system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        3x - 1y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        5x -8y -z \\
        -x + 1y +3z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        x+y+z \\ 
        3w -2y -z \\
        2w -x + 3y - 2z
    \end{array}
\right. $$

We could see that *A* is a system of 2 equations with 2 parameters. While *B* is a system of 3 equations with 3 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 3 & 5 \\ 8 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 13 & 16 & 18 \\ 13 & -12 & -11 \\ -11 & 14 & 12\end{bmatrix}\\
C=\begin{bmatrix} 31 & -62 & 53 & -84 \\ 15 & -26 & -17 & 68 \\ 39 & -11 & 33 & -5\end{bmatrix}
$$

So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.

# Declaring Matrices

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas *A* is a matrix consisting of elements denoted by aij . Denoted by i is the number of rows in the matrix while  stands for the number of columns.
Do note that the size of a matrix is i x j .

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using **shape, dimensions** and **size** attributes, we'll use them to analyze these matrices.

In [ ]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [6, 6]
])
describe_mat(A)

Matrix:
[[1 2]
 [6 6]]

Shape:	(2, 2)
Rank:	2



In [ ]:
G = np.array([
    [1,4],
    [2,9]
])
describe_mat(G)

Matrix:
[[1 4]
 [2 9]]

Shape:	(2, 2)
Rank:	2



In [ ]:
## Declaring a 3 x 2 matrix
B = np.array([
    [8, 3],
    [6, 2],
    [1, 1]
])
describe_mat(B)

Matrix:
[[8 3]
 [6 2]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H = np.array([1,9,8,7,6])
describe_mat(H)

Matrix:
[1 9 8 7 6]

Shape:	(5,)
Rank:	1



# Categorizing Matrices
There are several ways of classifying matrices. Once could be according to their **shape** and another is according to their **element values.** We'll try to go through them.

## According to shape

### Row and Column Matrices

Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be 1 x j and column matrices would be i x 1.

In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    2, 9, 5
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[2 9 5]

Shape:	(3,)
Rank:	1

Matrix:
[[1 2 3]]

Shape:	(1, 3)
Rank:	2



In [ ]:
## Declaring a Column Matrix

col_mat = np.array([
    [2],
    [6],
    [7]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[2]
 [6]
 [7]]

Shape:	(3, 1)
Rank:	2



### Square Matrices
Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if i = j. We can tweak our matrix descriptor function to determine square matrices.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
    [19,23,51],
    [34,36,81],
    [62,10,27]
])

non_square_mat = np.array([
    [11,21,53],
    [30,30,80]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[19 23 51]
 [34 36 81]
 [62 10 27]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[11 21 53]
 [30 30 80]]

Shape:	(2, 3)
Rank:	2
Is Square: False



### According to element values

#### Null Matrix
A Null matrix is a matrix that has no rows and no columns. It is used when you are analyzing a data set and you want to know what the dimensions of the data set are. 


In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


### Zero Matrices
A zero matrx can be any rectangular matrix but will all elements having a value of 0.

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


### Ones Matrix
A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


### Diagonal Matrix
The diagonal matrix is the identity matrix transposed. That is, the elements on the main diagonal are transposed with the elements on the other two diagonals. This matrix is useful for solving systems of linear equations.

In [ ]:
np.array([
    [5,3,2],
    [3,3,1],
    [0,0,5]
])

array([[5, 3, 2],
       [3, 3, 1],
       [0, 0, 5]])

In [ ]:
d = np.diag([4,3,6,8])
#d.shape[0] == d.shape[1]
d

array([[4, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

### Identity Matrix
An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(15)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

### Upper Triangular Matrix
An upper triangular matrix is a matrix that has no values below the diagonal.

In [ ]:
np.array([
    [1,2,3,4],
    [0,7,1,-1],
    [0,3,5,2],
    [1,6,4,2]
])

array([[ 1,  2,  3,  4],
       [ 0,  7,  1, -1],
       [ 0,  3,  5,  2],
       [ 1,  6,  4,  2]])

In [ ]:
F = np.array([
              [2, -3, 4, -5, 5],
              [8, -3, 4, -5, 6],
              [4, -2, 4, -6, 6],
              [1, -3, 4, -4, 6],
              [5, -6, 8, -5, 2],
])
np.triu(F)

array([[ 2, -3,  4, -5,  5],
       [ 0, -3,  4, -5,  6],
       [ 0,  0,  4, -6,  6],
       [ 0,  0,  0, -4,  6],
       [ 0,  0,  0,  0,  2]])

# Lower Triangular Matrix
A lower triangular matrix is a matrix that has no values above the diagonal

In [ ]:
np.tril(F)

array([[ 2,  0,  0,  0,  0],
       [ 8, -3,  0,  0,  0],
       [ 4, -2,  4,  0,  0],
       [ 1, -3,  4, -4,  0],
       [ 5, -6,  8, -5,  2]])

In [ ]:
np.array([
    [3,6,1],
    [0,7,9],
])

array([[3, 6, 1],
       [0, 7, 9]])

## Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

3. Given the matrix below, express it as a linear combination in a markdown.

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

# Matrix Algebra
Matrix algebra is the basis of many linear algebra algorithms. This section describes several matrix operations including transposition, matrix inversion, matrix exponentiation, and matrix multiplication. 


## Addition

In [ ]:
A = np.array([
    [1,5],
    [2,7],
    [4,8]
])
B = np.array([
    [0,3],
    [7,0],
    [7,1]
])
A+B

array([[ 1,  8],
       [ 9,  7],
       [11,  9]])

In [ ]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[ 3,  7],
       [ 4,  9],
       [ 6, 10]])

## Subtraction

In [ ]:
A-B

array([[ 1,  2],
       [-5,  7],
       [-3,  7]])

In [ ]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

# Element-wise Multiplication
Multiplying two matrices together element by element is often faster than multiplying them together with a scalar. The code below multiplies together two matrices using element-wise multiplication.

In [ ]:
A*B
np.multiply(A,B)

array([[ 0, 15],
       [14,  0],
       [28,  8]])

In [ ]:
2*A

array([[ 2, 10],
       [ 4, 14],
       [ 8, 16]])

In [ ]:
alpha=10**-10
A/(alpha+B)

array([[1.00000000e+10, 1.66666667e+00],
       [2.85714286e-01, 7.00000000e+10],
       [5.71428571e-01, 8.00000000e+00]])

In [ ]:
np.add(A,B)

array([[ 1,  8],
       [ 9,  7],
       [11,  9]])

# Activity

## Task 1
Create a function named mat_desc() that througouhly describes a matrix, it should:

1. Displays the shape, size, and rank of the matrix.
2. Displays whether the matrix is square or non-square.
3. Displays whether the matrix is an empty matrix.
4. Displays if the matrix is an identity, ones, or zeros matrix

Use 3 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [4]:
## Function area

import numpy as np

In [5]:
## Matrix Declarations

def mat_desc(mat):
    sq = False
    mat = np.array(mat)
    print(mat)
    print('Shape:', mat.shape)
    print('Size:', mat.size)
    print('Rank:', np.linalg.matrix_rank(mat))
    if(mat.shape[0] == mat.shape[1]):
        sq = True
        print('The matrix is square')
    else:
        print('The matrix is non-square')
    if(mat.shape[0] == 0 and mat.shape[1] == 0):
        print('The matrix is empty')
    else:
        print('The matrix is not empty')
    iden = np.identity(mat.shape[0])
    if(sq and (iden == mat).all()):
        print('The matrix is an identity matrix')
    else:
        print('The matrix is not an identity matrix')
    one = np.ones((mat.shape[0], mat.shape[1]))
    if((one == mat).all()):
        print('The matrix is an ones matrix')
    else:
        print('The matrix is not an ones matrix')
    zero = np.zeros((mat.shape[0], mat.shape[1]))
    if((zero == mat).all()):
        print('The matrix is an zeros matrix')
    else:
        print('The matrix is not a zeros matrix')

In [6]:
## Sample Matrices

print('Matrix 1:')
mat_desc([[3, 9, 5], [1, 4, 6], [6, 3, 7]])
print('Matrix 2:')
mat_desc([[5, 4, 9], [1, 4, 8], [9, 5, 8]])
print('Matrix 3:')
mat_desc([[1, 1, 3], [3, 3, 3], [6, 6, 6]])

Matrix 1:
[[3 9 5]
 [1 4 6]
 [6 3 7]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix
Matrix 2:
[[5 4 9]
 [1 4 8]
 [9 5 8]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix
Matrix 3:
[[1 1 3]
 [3 3 3]
 [6 6 6]]
Shape: (3, 3)
Size: 9
Rank: 2
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix


## Task 2

Create a  function named mat_operations() tht takes in two matrices in ynpyt marameters it should:
1. Determines if the matrices are vaable for operation and returns your own error message if they are not viable.
2. Returns the sum of the matrices.
3. Returns the difference of the matrices.
4. Returns the element-wise multiplication of the matrices.
5. Returns the element-wise division of the matrices.

Use 3 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [7]:
def mat_operations(mat1, mat2):
    mat1 = np.array(mat1)
    mat2 = np.array(mat2)
    print('Matrix 1:', mat1)
    print('Matrix 2:', mat2)
    if(mat1.shape != mat2.shape):
          print('The shape of both matrices are not same. Could not perform operations.')
          return
    print('Sum of the given matrices:')
    msum = mat1 + mat2
    print(msum)
    print('Difference of the given matrices:')
    mdiff = mat1 - mat2
    print(mdiff)
    print('Element-wise multiplication of the given matrices:')
    mmul = np.multiply(mat1, mat2)
    print(mmul)
    print('Element-wise division of the given matrices:')
    mmul = np.divide(mat1, mat2)
    print(mmul)

In [8]:
print('Sample 1:')
mat_operations([[1, 5, 5], [3, 4, 2], [4, 7, 8]], [[4, 4, 4], [5, 3, 3], [2, 2, 2]])
print('Sample 2:')
mat_operations([[1, 1, 1], [0, 0, 9], [4, 4, 4]], [[1, 1, 1], [6, 6, 6], [6, 6, 6]])
print('Sample 3:')
mat_operations([[1, 2, 1], [3, 3, 3], [6, 6, 6]], [[1, 1, 1], [7, 8, 7], [9, 8, 0]])

Sample 1:
Matrix 1: [[1 5 5]
 [3 4 2]
 [4 7 8]]
Matrix 2: [[4 4 4]
 [5 3 3]
 [2 2 2]]
Sum of the given matrices:
[[ 5  9  9]
 [ 8  7  5]
 [ 6  9 10]]
Difference of the given matrices:
[[-3  1  1]
 [-2  1 -1]
 [ 2  5  6]]
Element-wise multiplication of the given matrices:
[[ 4 20 20]
 [15 12  6]
 [ 8 14 16]]
Element-wise division of the given matrices:
[[0.25       1.25       1.25      ]
 [0.6        1.33333333 0.66666667]
 [2.         3.5        4.        ]]
Sample 2:
Matrix 1: [[1 1 1]
 [0 0 9]
 [4 4 4]]
Matrix 2: [[1 1 1]
 [6 6 6]
 [6 6 6]]
Sum of the given matrices:
[[ 2  2  2]
 [ 6  6 15]
 [10 10 10]]
Difference of the given matrices:
[[ 0  0  0]
 [-6 -6  3]
 [-2 -2 -2]]
Element-wise multiplication of the given matrices:
[[ 1  1  1]
 [ 0  0 54]
 [24 24 24]]
Element-wise division of the given matrices:
[[1.         1.         1.        ]
 [0.         0.         1.5       ]
 [0.66666667 0.66666667 0.66666667]]
Sample 3:
Matrix 1: [[1 2 1]
 [3 3 3]
 [6 6 6]]
Matrix 2: [[1 1 1]
 [7 8 7

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in true_divide
